# Generated by Django 5.1.9 on 2025-05-09 18:17

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=128)),
                ("date", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[("1", "Terror"), ("2", "Fantasia"), ("3", "Novela")],
                        max_length=16,
                    ),
                ),
                ("genre_other", models.CharField(blank=True, max_length=32, null=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
